services:
  - type: static
    name: 3d-sports-simulation
    buildCommand: npm install && npm run build
    publishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
